name: Deploy React app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - name: Install modules

        run: npm install
        with:
          path: "./where-its-at"
      - name: Build dist
        run: npm run build
        with:
          path: "./where-its-at"
      - name: Setup pages
        uses: actions/configure-pages@v3
      - name: Upload dist folder
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./where-its-at/dist"
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v1
